name: SQL Server to BigQuery Pipeline
on:
  schedule:
    - cron: '0 1 * * *'  # Exécuter tous les jours à 1h du matin
  workflow_dispatch:  # Lancer manuellement

jobs:
  etl_pipeline:
    runs-on: self-hosted  # Runner auto-hébergé
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Version spécifique

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Google Cloud credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: Set up environment variables
      run: |
        echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> $GITHUB_ENV
        echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> $GITHUB_ENV
        echo "SQL_USERNAME=${{ secrets.SQL_USERNAME }}" >> $GITHUB_ENV
        echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> $GITHUB_ENV
        echo "SQL_DRIVER=ODBC Driver 17 for SQL Server" >> $GITHUB_ENV
        echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
        echo "BQ_DATASET_ID=${{ secrets.BQ_DATASET_ID }}" >> $GITHUB_ENV
        echo "DATA_BASE_PATH=./data" >> $GITHUB_ENV

    - name: Run ETL pipeline
      run: python Script_python/pipeline_GCP.py

    - name: Run tests
      run: python -m pytest Script_python/tests/
