name: SQL Server to BigQuery Pipeline

on:
  schedule:
    - cron: '0 1 * * *' # Exécution quotidienne à 1h du matin
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  etl_pipeline:
    runs-on: self-hosted  # Utilisation du runner local
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      shell: pwsh
      run: |
        try {
          python --version
        } catch {
          Write-Output "Python is not installed on the self-hosted runner"
          exit 1
        }

    - name: Install dependencies
      shell: pwsh
      run: |
        pip install -r requirements.txt

    - name: Configure Google Cloud credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up environment variables
      shell: pwsh
      run: |
        "SQL_SERVER=localhost,1433" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "SQL_USERNAME=${{ secrets.SQL_USERNAME }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "SQL_DRIVER=${{ secrets.SQL_DRIVER }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "BQ_DATASET_ID=${{ secrets.BQ_DATASET_ID }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "DATA_BASE_PATH=./data" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Run ETL pipeline
      shell: pwsh
      run: python Script_python/pipeline_GCP.py

    - name: Run tests
      shell: pwsh
      run: python Script_python/pytest.py
