name: SQL Server to BigQuery Pipeline
on:
  schedule:
    - cron: '0 1 * * *'  # Run daily at 1 AM
  workflow_dispatch:  # Allow manual triggering
jobs:
  etl_pipeline:
    runs-on: self-hosted  # Using local runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      run: |
        # Check if Python is installed (compatible with both bash and PowerShell)
        which python3 || which python || echo "Python not found"
        python3 --version || python --version || echo "Python version check failed"
      shell: bash
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt || pip3 install -r requirements.txt
      shell: bash
      
    - name: Configure Google Cloud credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        
    - name: Set up environment variables
      run: |
        echo "SQL_SERVER=localhost,1433" >> $GITHUB_ENV
        echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> $GITHUB_ENV
        echo "SQL_USERNAME=${{ secrets.SQL_USERNAME }}" >> $GITHUB_ENV
        echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> $GITHUB_ENV
        echo "SQL_DRIVER=${{ secrets.SQL_DRIVER }}" >> $GITHUB_ENV
        echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
        echo "BQ_DATASET_ID=${{ secrets.BQ_DATASET_ID }}" >> $GITHUB_ENV
        echo "DATA_BASE_PATH=./data" >> $GITHUB_ENV
      shell: bash
      
    - name: Run ETL pipeline
      run: python Script_python/pipeline_GCP.py || python3 Script_python/pipeline_GCP.py
      shell: bash
      
    - name: Run tests
      run: python Script_python/pytest.py || python3 Script_python/pytest.py
      shell: bash
