name: SQL Server to BigQuery Pipeline

on:
  schedule:
    - cron: '0 1 * * *'  # Exécution quotidienne à 1h du matin
  workflow_dispatch:     # Permet le déclenchement manuel

jobs:
  etl_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
   
          pip install -r requirements.txt
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

      - name: Configure Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up environment variables
        run: |
          echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> $GITHUB_ENV
          echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> $GITHUB_ENV
          echo "SQL_USERNAME=${{ secrets.SQL_USERNAME }}" >> $GITHUB_ENV
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> $GITHUB_ENV
          echo "SQL_DRIVER=${{ secrets.SQL_DRIVER }}" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=${{ secrets.BQ_DATASET_ID }}" >> $GITHUB_ENV

      - name: Run ETL pipeline
        run: python Script_python/pipeline_GCP.py

      - name: Run tests
        run: python Script_python/pytest.py
